[package]
name = "poeiter"
version = "0.1.0"
authors = ["valdron <seehofer.paul@gmail.com>"]

[dependencies]
timed_iterator = { git = "https://github.com/valdron/timed_iterator.git" }
serde = ""
serde_json = ""
serde_derive = ""
regex = ""
reqwest = ""
lazy_static = ""
error-chain = ""
